spring:
  profiles:
    active: db, core, wx
  messages:
    encoding: UTF-8
  jackson:
    time-zone: GMT+8

server:
  port: 8082

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall.wx:  INFO
    org.linlinjava.litemall:  ERROR
    org.linlinjava.litemall.db.dao:  DEBUG
    config: ./logback.xml